language: scala
sudo: false

scala:
  - 2.13.3
  - 2.12.12
  - 2.11.12
jdk:
  - openjdk8

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/f1a7ec8fc9a34c6a9108
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false

env:
  global:
    - MAIN_SCALA_VERSION=2.13.3

script:
  - project/travis-build.sh
after_success:
  - project/travis-post-build.sh

cache:
  directories:
  - $HOME/.sbt/1.0
  - $HOME/.sbt/boot/scala*
  - $HOME/.sbt/cache
  - $HOME/.sbt/launchers
  - $HOME/.ivy2

before_cache:
  - du -h -d 1 $HOME/.ivy2/
  - du -h -d 2 $HOME/.sbt/
  - find $HOME/.sbt -name "*.lock" -type f -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
