addSbtPlugin("com.jsuereth"       %  "sbt-pgp"               % "2.0.1")
addSbtPlugin("com.github.gseitz"  %  "sbt-release"           % "1.0.13")
addSbtPlugin("org.xerial.sbt"     %  "sbt-sonatype"          % "3.9.2")
addSbtPlugin("org.scoverage"      %  "sbt-scoverage"         % "1.6.1")
addSbtPlugin("com.typesafe"       %  "sbt-mima-plugin"       % "0.7.0")
addSbtPlugin("org.scalariform"    %  "sbt-scalariform"       % "1.8.3")
addSbtPlugin("pl.project13.scala" %  "sbt-jmh"               % "0.3.7")
