addSbtPlugin("com.jsuereth"       %  "sbt-pgp"               % "1.1.0")
addSbtPlugin("com.github.gseitz"  %  "sbt-release"           % "1.0.7")
addSbtPlugin("org.xerial.sbt"     %  "sbt-sonatype"          % "2.1")
addSbtPlugin("org.scoverage"      %  "sbt-scoverage"         % "1.5.1")
addSbtPlugin("com.typesafe"       %  "sbt-mima-plugin"       % "0.1.14")
addSbtPlugin("org.scalariform"    %  "sbt-scalariform"       % "1.8.2")
addSbtPlugin("pl.project13.scala" %  "sbt-jmh"               % "0.2.27")
